### ISSUE TITLE
Add debugging information to DecodingException

### ISSUE THREAD

**Issue by mrumpf** [preon/preon#26]
I found it quite hard to associate a decoding error with the field being decoded.
Would it be possible to add the name of the field being decoded to the DecodingException?

**Comment by thorstenfrank** [comment]
Fixed in version 2.0.0, see https://github.com/thorstenfrank/preon/commit/be61b382c1a76b8a60d3d644dcad7290d806d3d9

Decoding exception stack traces will now include the current field and type, e.g.

```
org.codehaus.preon.DecodingException: Error decoding field [eggs] in type [Spam]
	at org.codehaus.preon.binding.StandardBindingFactory$FieldBinding.load(StandardBindingFactory.java:79)
...
Caused by: org.codehaus.preon.buffer.BitBufferUnderflowException: Failed to read 3 bits from position 17
...
```
